package domain;

// Generated 17.06.2014 16:40:12 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Viewobject generated by hbm2java
 */
@Entity
@Table(name = "viewobject", catalog = "trolley", uniqueConstraints = @UniqueConstraint(columnNames = {
		"viewId", "objType", "objId" }))
public class Viewobject implements java.io.Serializable {

	private ViewobjectId id;
	private View view;
	private Catobject catobject;

	public Viewobject() {
	}

	public Viewobject(ViewobjectId id, View view, Catobject catobject) {
		this.id = id;
		this.view = view;
		this.catobject = catobject;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "viewId", column = @Column(name = "viewId", nullable = false)),
			@AttributeOverride(name = "objType", column = @Column(name = "objType", nullable = false)),
			@AttributeOverride(name = "objId", column = @Column(name = "objId", nullable = false)),
			@AttributeOverride(name = "pos", column = @Column(name = "pos", nullable = false, precision = 4)) })
	public ViewobjectId getId() {
		return this.id;
	}

	public void setId(ViewobjectId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "viewId", nullable = false, insertable = false, updatable = false)
	public View getView() {
		return this.view;
	}

	public void setView(View view) {
		this.view = view;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "objType", nullable = false, insertable = false, updatable = false)
	public Catobject getCatobject() {
		return this.catobject;
	}

	public void setCatobject(Catobject catobject) {
		this.catobject = catobject;
	}

}
