package domain;

// Generated 17.06.2014 13:52:54 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bus generated by hbm2java
 */
@Entity
@Table(name = "bus", catalog = "trolley")
public class Bus implements java.io.Serializable {

	private Integer id;
	private Catmodel catmodel;
	private int serial;
	private String serialAlt;
	private Integer manM;
	private Date manY;
	private Integer overM;
	private Date overY;
	private Set buschanges = new HashSet(0);

	public Bus() {
	}

	public Bus(Catmodel catmodel, int serial, String serialAlt) {
		this.catmodel = catmodel;
		this.serial = serial;
		this.serialAlt = serialAlt;
	}

	public Bus(Catmodel catmodel, int serial, String serialAlt, Integer manM,
			Date manY, Integer overM, Date overY, Set buschanges) {
		this.catmodel = catmodel;
		this.serial = serial;
		this.serialAlt = serialAlt;
		this.manM = manM;
		this.manY = manY;
		this.overM = overM;
		this.overY = overY;
		this.buschanges = buschanges;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelId", nullable = false)
	public Catmodel getCatmodel() {
		return this.catmodel;
	}

	public void setCatmodel(Catmodel catmodel) {
		this.catmodel = catmodel;
	}

	@Column(name = "serial", nullable = false)
	public int getSerial() {
		return this.serial;
	}

	public void setSerial(int serial) {
		this.serial = serial;
	}

	@Column(name = "serialAlt", nullable = false, length = 50)
	public String getSerialAlt() {
		return this.serialAlt;
	}

	public void setSerialAlt(String serialAlt) {
		this.serialAlt = serialAlt;
	}

	@Column(name = "manM")
	public Integer getManM() {
		return this.manM;
	}

	public void setManM(Integer manM) {
		this.manM = manM;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "manY", length = 0)
	public Date getManY() {
		return this.manY;
	}

	public void setManY(Date manY) {
		this.manY = manY;
	}

	@Column(name = "overM")
	public Integer getOverM() {
		return this.overM;
	}

	public void setOverM(Integer overM) {
		this.overM = overM;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "overY", length = 0)
	public Date getOverY() {
		return this.overY;
	}

	public void setOverY(Date overY) {
		this.overY = overY;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bus")
	public Set getBuschanges() {
		return this.buschanges;
	}

	public void setBuschanges(Set buschanges) {
		this.buschanges = buschanges;
	}

}
