package domain;

// Generated 17.06.2014 13:52:54 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Buschange generated by hbm2java
 */
@Entity
@Table(name = "buschange", catalog = "trolley")
public class Buschange implements java.io.Serializable {

	private Integer id;
	private Bus bus;
	private Event event;
	private Catdepo catdepoByDepoId;
	private Catdepo catdepoByDepoMain;
	private Catbustype catbustype;
	private Catbort catbort;
	private Catstatus catstatus;

	public Buschange() {
	}

	public Buschange(Bus bus, Event event, Catdepo catdepoByDepoId,
			Catdepo catdepoByDepoMain, Catbustype catbustype, Catbort catbort,
			Catstatus catstatus) {
		this.bus = bus;
		this.event = event;
		this.catdepoByDepoId = catdepoByDepoId;
		this.catdepoByDepoMain = catdepoByDepoMain;
		this.catbustype = catbustype;
		this.catbort = catbort;
		this.catstatus = catstatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "busId", nullable = false)
	public Bus getBus() {
		return this.bus;
	}

	public void setBus(Bus bus) {
		this.bus = bus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eventId", nullable = false)
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "depoId", nullable = false)
	public Catdepo getCatdepoByDepoId() {
		return this.catdepoByDepoId;
	}

	public void setCatdepoByDepoId(Catdepo catdepoByDepoId) {
		this.catdepoByDepoId = catdepoByDepoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "depoMain", nullable = false)
	public Catdepo getCatdepoByDepoMain() {
		return this.catdepoByDepoMain;
	}

	public void setCatdepoByDepoMain(Catdepo catdepoByDepoMain) {
		this.catdepoByDepoMain = catdepoByDepoMain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeId", nullable = false)
	public Catbustype getCatbustype() {
		return this.catbustype;
	}

	public void setCatbustype(Catbustype catbustype) {
		this.catbustype = catbustype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bortId", nullable = false)
	public Catbort getCatbort() {
		return this.catbort;
	}

	public void setCatbort(Catbort catbort) {
		this.catbort = catbort;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "statusId", nullable = false)
	public Catstatus getCatstatus() {
		return this.catstatus;
	}

	public void setCatstatus(Catstatus catstatus) {
		this.catstatus = catstatus;
	}

}
