package domain;

// Generated 17.06.2014 13:52:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Catbustype generated by hbm2java
 */
@Entity
@Table(name = "catbustype", catalog = "trolley")
public class Catbustype implements java.io.Serializable {

	private Integer id;
	private String type;
	private Set buschanges = new HashSet(0);

	public Catbustype() {
	}

	public Catbustype(String type, Set buschanges) {
		this.type = type;
		this.buschanges = buschanges;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catbustype")
	public Set getBuschanges() {
		return this.buschanges;
	}

	public void setBuschanges(Set buschanges) {
		this.buschanges = buschanges;
	}

}
