package domain;

// Generated 17.06.2014 13:52:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Catmodel generated by hbm2java
 */
@Entity
@Table(name = "catmodel", catalog = "trolley")
public class Catmodel implements java.io.Serializable {

	private Integer id;
	private Catmaker catmaker;
	private String text;
	private String textAlt;
	private Set buses = new HashSet(0);

	public Catmodel() {
	}

	public Catmodel(Catmaker catmaker, String text) {
		this.catmaker = catmaker;
		this.text = text;
	}

	public Catmodel(Catmaker catmaker, String text, String textAlt, Set buses) {
		this.catmaker = catmaker;
		this.text = text;
		this.textAlt = textAlt;
		this.buses = buses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "makerId", nullable = false)
	public Catmaker getCatmaker() {
		return this.catmaker;
	}

	public void setCatmaker(Catmaker catmaker) {
		this.catmaker = catmaker;
	}

	@Column(name = "text", nullable = false, length = 50)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "textAlt", length = 50)
	public String getTextAlt() {
		return this.textAlt;
	}

	public void setTextAlt(String textAlt) {
		this.textAlt = textAlt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catmodel")
	public Set getBuses() {
		return this.buses;
	}

	public void setBuses(Set buses) {
		this.buses = buses;
	}

}
