package domain;

// Generated 17.06.2014 13:52:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Catstatus generated by hbm2java
 */
@Entity
@Table(name = "catstatus", catalog = "trolley")
public class Catstatus implements java.io.Serializable {

	private Integer id;
	private String text;
	private Set buschanges = new HashSet(0);

	public Catstatus() {
	}

	public Catstatus(String text) {
		this.text = text;
	}

	public Catstatus(String text, Set buschanges) {
		this.text = text;
		this.buschanges = buschanges;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "text", nullable = false, length = 50)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catstatus")
	public Set getBuschanges() {
		return this.buschanges;
	}

	public void setBuschanges(Set buschanges) {
		this.buschanges = buschanges;
	}

}
