package domain;

// Generated 17.06.2014 13:52:54 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "trolley")
public class Event implements java.io.Serializable {

	private Integer id;
	private Catevent catevent;
	private Integer day;
	private Integer month;
	private Date year;
	private String text;
	private Set eventobjects = new HashSet(0);
	private Set buschanges = new HashSet(0);

	public Event() {
	}

	public Event(Catevent catevent, String text) {
		this.catevent = catevent;
		this.text = text;
	}

	public Event(Catevent catevent, Integer day, Integer month, Date year,
			String text, Set eventobjects, Set buschanges) {
		this.catevent = catevent;
		this.day = day;
		this.month = month;
		this.year = year;
		this.text = text;
		this.eventobjects = eventobjects;
		this.buschanges = buschanges;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeId", nullable = false)
	public Catevent getCatevent() {
		return this.catevent;
	}

	public void setCatevent(Catevent catevent) {
		this.catevent = catevent;
	}

	@Column(name = "day")
	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	@Column(name = "month")
	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "year", length = 0)
	public Date getYear() {
		return this.year;
	}

	public void setYear(Date year) {
		this.year = year;
	}

	@Column(name = "text", nullable = false, length = 65535)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	public Set getEventobjects() {
		return this.eventobjects;
	}

	public void setEventobjects(Set eventobjects) {
		this.eventobjects = eventobjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	public Set getBuschanges() {
		return this.buschanges;
	}

	public void setBuschanges(Set buschanges) {
		this.buschanges = buschanges;
	}

}
