package domain;

// Generated 09.06.2014 23:05:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bus generated by hbm2java
 */
@Entity
@Table(name = "bus", catalog = "trolley")
public class Bus implements java.io.Serializable {

	private Integer id;
	private CatModel catModel;
	private int serial;
	private String serialAlt;
	private Integer manM;
	private Date manY;
	private Integer overM;
	private Date overY;
	private Set busChanges = new HashSet(0);

	public Bus() {
	}

	public Bus(CatModel catModel, int serial, String serialAlt) {
		this.catModel = catModel;
		this.serial = serial;
		this.serialAlt = serialAlt;
	}

	public Bus(CatModel catModel, int serial, String serialAlt, Integer manM,
			Date manY, Integer overM, Date overY, Set busChanges) {
		this.catModel = catModel;
		this.serial = serial;
		this.serialAlt = serialAlt;
		this.manM = manM;
		this.manY = manY;
		this.overM = overM;
		this.overY = overY;
		this.busChanges = busChanges;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modelID", nullable = false)
	public CatModel getCatModel() {
		return this.catModel;
	}

	public void setCatModel(CatModel catModel) {
		this.catModel = catModel;
	}

	@Column(name = "serial", nullable = false)
	public int getSerial() {
		return this.serial;
	}

	public void setSerial(int serial) {
		this.serial = serial;
	}

	@Column(name = "serialAlt", nullable = false, length = 32)
	public String getSerialAlt() {
		return this.serialAlt;
	}

	public void setSerialAlt(String serialAlt) {
		this.serialAlt = serialAlt;
	}

	@Column(name = "manM")
	public Integer getManM() {
		return this.manM;
	}

	public void setManM(Integer manM) {
		this.manM = manM;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "manY", length = 0)
	public Date getManY() {
		return this.manY;
	}

	public void setManY(Date manY) {
		this.manY = manY;
	}

	@Column(name = "overM")
	public Integer getOverM() {
		return this.overM;
	}

	public void setOverM(Integer overM) {
		this.overM = overM;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "overY", length = 0)
	public Date getOverY() {
		return this.overY;
	}

	public void setOverY(Date overY) {
		this.overY = overY;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bus")
	public Set getBusChanges() {
		return this.busChanges;
	}

	public void setBusChanges(Set busChanges) {
		this.busChanges = busChanges;
	}

}
