package domain;

// Generated 09.06.2014 23:05:54 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BusChange generated by hbm2java
 */
@Entity
@Table(name = "bus-change", catalog = "trolley")
public class BusChange implements java.io.Serializable {

	private Integer id;
	private Bus bus;
	private Event event;
	private CatDepo catDepoByDepoId;
	private CatDepo catDepoByDepoMain;
	private CatBustype catBustype;
	private CatBort catBort;
	private CatStatus catStatus;

	public BusChange() {
	}

	public BusChange(Bus bus, Event event, CatDepo catDepoByDepoId,
			CatDepo catDepoByDepoMain, CatBustype catBustype, CatBort catBort,
			CatStatus catStatus) {
		this.bus = bus;
		this.event = event;
		this.catDepoByDepoId = catDepoByDepoId;
		this.catDepoByDepoMain = catDepoByDepoMain;
		this.catBustype = catBustype;
		this.catBort = catBort;
		this.catStatus = catStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "busID", nullable = false)
	public Bus getBus() {
		return this.bus;
	}

	public void setBus(Bus bus) {
		this.bus = bus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eventID", nullable = false)
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "depoID", nullable = false)
	public CatDepo getCatDepoByDepoId() {
		return this.catDepoByDepoId;
	}

	public void setCatDepoByDepoId(CatDepo catDepoByDepoId) {
		this.catDepoByDepoId = catDepoByDepoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "depoMain", nullable = false)
	public CatDepo getCatDepoByDepoMain() {
		return this.catDepoByDepoMain;
	}

	public void setCatDepoByDepoMain(CatDepo catDepoByDepoMain) {
		this.catDepoByDepoMain = catDepoByDepoMain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeID", nullable = false)
	public CatBustype getCatBustype() {
		return this.catBustype;
	}

	public void setCatBustype(CatBustype catBustype) {
		this.catBustype = catBustype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bortID", nullable = false)
	public CatBort getCatBort() {
		return this.catBort;
	}

	public void setCatBort(CatBort catBort) {
		this.catBort = catBort;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "statusID", nullable = false)
	public CatStatus getCatStatus() {
		return this.catStatus;
	}

	public void setCatStatus(CatStatus catStatus) {
		this.catStatus = catStatus;
	}

}
