package domain;

// Generated 09.06.2014 23:05:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatBort generated by hbm2java
 */
@Entity
@Table(name = "cat-bort", catalog = "trolley")
public class CatBort implements java.io.Serializable {

	private Integer id;
	private String text;
	private Set busChanges = new HashSet(0);

	public CatBort() {
	}

	public CatBort(String text) {
		this.text = text;
	}

	public CatBort(String text, Set busChanges) {
		this.text = text;
		this.busChanges = busChanges;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "text", nullable = false, length = 4)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catBort")
	public Set getBusChanges() {
		return this.busChanges;
	}

	public void setBusChanges(Set busChanges) {
		this.busChanges = busChanges;
	}

}
