package domain;

// Generated 09.06.2014 23:05:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatBustype generated by hbm2java
 */
@Entity
@Table(name = "cat-bustype", catalog = "trolley")
public class CatBustype implements java.io.Serializable {

	private Integer id;
	private String type;
	private Set busChanges = new HashSet(0);

	public CatBustype() {
	}

	public CatBustype(String type, Set busChanges) {
		this.type = type;
		this.busChanges = busChanges;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catBustype")
	public Set getBusChanges() {
		return this.busChanges;
	}

	public void setBusChanges(Set busChanges) {
		this.busChanges = busChanges;
	}

}
