package domain;

// Generated 09.06.2014 23:05:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatDepo generated by hbm2java
 */
@Entity
@Table(name = "cat-depo", catalog = "trolley")
public class CatDepo implements java.io.Serializable {

	private Integer id;
	private String text;
	private String textAlt;
	private Set busChangesForDepoId = new HashSet(0);
	private Set busChangesForDepoMain = new HashSet(0);

	public CatDepo() {
	}

	public CatDepo(String text, String textAlt) {
		this.text = text;
		this.textAlt = textAlt;
	}

	public CatDepo(String text, String textAlt, Set busChangesForDepoId,
			Set busChangesForDepoMain) {
		this.text = text;
		this.textAlt = textAlt;
		this.busChangesForDepoId = busChangesForDepoId;
		this.busChangesForDepoMain = busChangesForDepoMain;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "text", nullable = false, length = 50)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "textAlt", nullable = false, length = 50)
	public String getTextAlt() {
		return this.textAlt;
	}

	public void setTextAlt(String textAlt) {
		this.textAlt = textAlt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catDepoByDepoId")
	public Set getBusChangesForDepoId() {
		return this.busChangesForDepoId;
	}

	public void setBusChangesForDepoId(Set busChangesForDepoId) {
		this.busChangesForDepoId = busChangesForDepoId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catDepoByDepoMain")
	public Set getBusChangesForDepoMain() {
		return this.busChangesForDepoMain;
	}

	public void setBusChangesForDepoMain(Set busChangesForDepoMain) {
		this.busChangesForDepoMain = busChangesForDepoMain;
	}

}
