package domain;

// Generated 09.06.2014 23:05:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatMaker generated by hbm2java
 */
@Entity
@Table(name = "cat-maker", catalog = "trolley")
public class CatMaker implements java.io.Serializable {

	private Integer id;
	private String text;
	private String textAlt;
	private Set catModels = new HashSet(0);

	public CatMaker() {
	}

	public CatMaker(String text, String textAlt) {
		this.text = text;
		this.textAlt = textAlt;
	}

	public CatMaker(String text, String textAlt, Set catModels) {
		this.text = text;
		this.textAlt = textAlt;
		this.catModels = catModels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "text", nullable = false, length = 50)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "textAlt", nullable = false, length = 50)
	public String getTextAlt() {
		return this.textAlt;
	}

	public void setTextAlt(String textAlt) {
		this.textAlt = textAlt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catMaker")
	public Set getCatModels() {
		return this.catModels;
	}

	public void setCatModels(Set catModels) {
		this.catModels = catModels;
	}

}
