package domain;

// Generated 09.06.2014 23:05:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatObject generated by hbm2java
 */
@Entity
@Table(name = "cat-object", catalog = "trolley")
public class CatObject implements java.io.Serializable {

	private Integer id;
	private String text;
	private Set eventObjects = new HashSet(0);
	private Set viewObjects = new HashSet(0);

	public CatObject() {
	}

	public CatObject(String text) {
		this.text = text;
	}

	public CatObject(String text, Set eventObjects, Set viewObjects) {
		this.text = text;
		this.eventObjects = eventObjects;
		this.viewObjects = viewObjects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "text", nullable = false, length = 50)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catObject")
	public Set getEventObjects() {
		return this.eventObjects;
	}

	public void setEventObjects(Set eventObjects) {
		this.eventObjects = eventObjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catObject")
	public Set getViewObjects() {
		return this.viewObjects;
	}

	public void setViewObjects(Set viewObjects) {
		this.viewObjects = viewObjects;
	}

}
