package domain;

// Generated 09.06.2014 23:05:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "trolley")
public class Event implements java.io.Serializable {

	private Integer id;
	private CatEvent catEvent;
	private Integer day;
	private Integer month;
	private Date year;
	private String text;
	private Set eventObjects = new HashSet(0);
	private Set busChanges = new HashSet(0);

	public Event() {
	}

	public Event(CatEvent catEvent, String text) {
		this.catEvent = catEvent;
		this.text = text;
	}

	public Event(CatEvent catEvent, Integer day, Integer month, Date year,
			String text, Set eventObjects, Set busChanges) {
		this.catEvent = catEvent;
		this.day = day;
		this.month = month;
		this.year = year;
		this.text = text;
		this.eventObjects = eventObjects;
		this.busChanges = busChanges;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeID", nullable = false)
	public CatEvent getCatEvent() {
		return this.catEvent;
	}

	public void setCatEvent(CatEvent catEvent) {
		this.catEvent = catEvent;
	}

	@Column(name = "day")
	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	@Column(name = "month")
	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "year", length = 0)
	public Date getYear() {
		return this.year;
	}

	public void setYear(Date year) {
		this.year = year;
	}

	@Column(name = "text", nullable = false, length = 65535)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	public Set getEventObjects() {
		return this.eventObjects;
	}

	public void setEventObjects(Set eventObjects) {
		this.eventObjects = eventObjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	public Set getBusChanges() {
		return this.busChanges;
	}

	public void setBusChanges(Set busChanges) {
		this.busChanges = busChanges;
	}

}
