package domain;

// Generated 09.06.2014 23:05:54 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EventObject generated by hbm2java
 */
@Entity
@Table(name = "event-object", catalog = "trolley", uniqueConstraints = @UniqueConstraint(columnNames = {
		"eventID", "objType", "objID" }))
public class EventObject implements java.io.Serializable {

	private EventObjectId id;
	private Event event;
	private CatObject catObject;

	public EventObject() {
	}

	public EventObject(EventObjectId id, Event event, CatObject catObject) {
		this.id = id;
		this.event = event;
		this.catObject = catObject;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "eventId", column = @Column(name = "eventID", nullable = false)),
			@AttributeOverride(name = "objType", column = @Column(name = "objType", nullable = false)),
			@AttributeOverride(name = "objId", column = @Column(name = "objID", nullable = false)) })
	public EventObjectId getId() {
		return this.id;
	}

	public void setId(EventObjectId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eventID", nullable = false, insertable = false, updatable = false)
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "objType", nullable = false, insertable = false, updatable = false)
	public CatObject getCatObject() {
		return this.catObject;
	}

	public void setCatObject(CatObject catObject) {
		this.catObject = catObject;
	}

}
