package domain;

// Generated 09.06.2014 23:05:54 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventObjectId generated by hbm2java
 */
@Embeddable
public class EventObjectId implements java.io.Serializable {

	private int eventId;
	private int objType;
	private int objId;

	public EventObjectId() {
	}

	public EventObjectId(int eventId, int objType, int objId) {
		this.eventId = eventId;
		this.objType = objType;
		this.objId = objId;
	}

	@Column(name = "eventID", nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@Column(name = "objType", nullable = false)
	public int getObjType() {
		return this.objType;
	}

	public void setObjType(int objType) {
		this.objType = objType;
	}

	@Column(name = "objID", nullable = false)
	public int getObjId() {
		return this.objId;
	}

	public void setObjId(int objId) {
		this.objId = objId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventObjectId))
			return false;
		EventObjectId castOther = (EventObjectId) other;

		return (this.getEventId() == castOther.getEventId())
				&& (this.getObjType() == castOther.getObjType())
				&& (this.getObjId() == castOther.getObjId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEventId();
		result = 37 * result + this.getObjType();
		result = 37 * result + this.getObjId();
		return result;
	}

}
