package domain;

// Generated 09.06.2014 23:05:54 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ViewObject generated by hbm2java
 */
@Entity
@Table(name = "view-object", catalog = "trolley", uniqueConstraints = @UniqueConstraint(columnNames = {
		"viewID", "objType", "objID" }))
public class ViewObject implements java.io.Serializable {

	private ViewObjectId id;
	private View view;
	private CatObject catObject;

	public ViewObject() {
	}

	public ViewObject(ViewObjectId id, View view, CatObject catObject) {
		this.id = id;
		this.view = view;
		this.catObject = catObject;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "viewId", column = @Column(name = "viewID", nullable = false)),
			@AttributeOverride(name = "objType", column = @Column(name = "objType", nullable = false)),
			@AttributeOverride(name = "objId", column = @Column(name = "objID", nullable = false)),
			@AttributeOverride(name = "pos", column = @Column(name = "pos", nullable = false, precision = 4)) })
	public ViewObjectId getId() {
		return this.id;
	}

	public void setId(ViewObjectId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "viewID", nullable = false, insertable = false, updatable = false)
	public View getView() {
		return this.view;
	}

	public void setView(View view) {
		this.view = view;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "objType", nullable = false, insertable = false, updatable = false)
	public CatObject getCatObject() {
		return this.catObject;
	}

	public void setCatObject(CatObject catObject) {
		this.catObject = catObject;
	}

}
