package domain;

// Generated 09.06.2014 23:05:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * View generated by hbm2java
 */
@Entity
@Table(name = "view", catalog = "trolley")
public class View implements java.io.Serializable {

	private Integer id;
	private CatVaccess catVaccess;
	private CatVowner catVowner;
	private CatVtype catVtype;
	private String path;
	private String color;
	private String text;
	private Integer day;
	private Integer month;
	private Date year;
	private Set viewObjects = new HashSet(0);

	public View() {
	}

	public View(CatVaccess catVaccess, CatVowner catVowner, CatVtype catVtype,
			String path, String color, String text) {
		this.catVaccess = catVaccess;
		this.catVowner = catVowner;
		this.catVtype = catVtype;
		this.path = path;
		this.color = color;
		this.text = text;
	}

	public View(CatVaccess catVaccess, CatVowner catVowner, CatVtype catVtype,
			String path, String color, String text, Integer day, Integer month,
			Date year, Set viewObjects) {
		this.catVaccess = catVaccess;
		this.catVowner = catVowner;
		this.catVtype = catVtype;
		this.path = path;
		this.color = color;
		this.text = text;
		this.day = day;
		this.month = month;
		this.year = year;
		this.viewObjects = viewObjects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "access", nullable = false)
	public CatVaccess getCatVaccess() {
		return this.catVaccess;
	}

	public void setCatVaccess(CatVaccess catVaccess) {
		this.catVaccess = catVaccess;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner", nullable = false)
	public CatVowner getCatVowner() {
		return this.catVowner;
	}

	public void setCatVowner(CatVowner catVowner) {
		this.catVowner = catVowner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type", nullable = false)
	public CatVtype getCatVtype() {
		return this.catVtype;
	}

	public void setCatVtype(CatVtype catVtype) {
		this.catVtype = catVtype;
	}

	@Column(name = "path", nullable = false, length = 50)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "color", nullable = false, length = 50)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "text", nullable = false, length = 65535)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "day")
	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	@Column(name = "month")
	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "year", length = 0)
	public Date getYear() {
		return this.year;
	}

	public void setYear(Date year) {
		this.year = year;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "view")
	public Set getViewObjects() {
		return this.viewObjects;
	}

	public void setViewObjects(Set viewObjects) {
		this.viewObjects = viewObjects;
	}

}
